### ISSUE TITLE
Display white/blank screen after end of auctions

### ISSUE THREAD

**Issue by nekofar** [lilnounsDAO/lilnouns-monorepo#106]
https://discord.com/channels/954142017556979752/975881980950511646/1011822309985767554

> Is there anyone else experiencing white screens after ending auctions? It does happen to me multiple times, I thought it could be my connection issue, so I didn’t look at that. I just saw someone else mention white screens and remembered that.

![](https://cdn.discordapp.com/attachments/975881980950511646/1013530724172845096/image0.jpg)

**Comment by lilnounsDAO** [comment]
https://github.com/lilnounsDAO/lilnouns-monorepo/commit/cd441a073bf6bce622b238065d50dd4d92c41986
